server:
  port: 8085

spring:
  data:
    mongodb:
      authentication-database: admin
      username: admin
      password: password
      database: sharing-system
      port: 27017
      host: localhost
  graphql:
    graphiql:
      enabled: true
      path: /graphiql


dgs:
  graphql:
    extensions:
      scalars:
        objects:
          enabled: true