package com.sharingsystem.poc.model.common;

public enum EOrganisationUserStatus {
    USER_INVITE_PENDING, USER_INVITE_OKID_PENDING, USER_INVITE_EMAIL_PENDING, USER_INVITE_MOBILE_PENDING,
    USER_INVITE_BLOCKED, ORGANISATION_JOIN_REQUEST_PENDING, ORGANISATION_JOIN_REQUEST_BLOCKED, ACTIVE;
}
