package com.sharingsystem.poc.model.common;

public enum EOrganisationRole {
    INSPECTION_LOG_INSPECTOR, INSPECTION_LOG_ASSIGNEE, ORGANISATION_USER, ORGANISATION_COWORKER, ORGANISATION_MANAGER, ORGANISATION_OWNER;
}
